# Generated by Django 4.2.7 on 2023-11-27 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('things', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thing',
            name='description',
            field=models.TextField(blank=True, error_messages={'Description must not have more than 120 characters'}, max_length=120),
        ),
    ]
